In [0]:
#Importing Libraries
import numpy as np
import pandas as pd

In [0]:
df=pd.read_csv("gait.csv",names=["RH","LH","RK","LK","RA","LA","class"])

In [0]:
df.head()

RH     LH     RK     LK    RA    LA  class
0  24.61 -16.56  -3.94  -8.20 -1.70  9.81      0
1  24.45 -16.82  -6.66 -11.29 -3.25  8.26      0
2  24.13 -16.53  -9.45 -15.19 -4.68  5.52      0
3  23.68 -15.40 -12.26 -20.17 -5.08  1.11      0
4  22.96 -13.44 -14.76 -26.06 -4.17 -4.36      0

In [6]:
df.describe()

RH          LH          RK          LK          RA          LA  \
count  194.000000  194.000000  194.000000  194.000000  194.000000  194.000000   
mean     4.753114    3.894876  -22.831523  -20.170355    3.108274    0.699646   
std     15.544316   15.971763   20.869358   22.104877    6.019425    5.358262   
min    -21.978791  -23.849198  -69.740606  -68.433772  -14.070000  -14.070000   
25%    -10.146497  -10.786888  -33.700926  -34.560000   -0.007475   -3.091769   
50%      8.383730    7.659724  -15.376424  -12.436281    2.134878    0.361346   
75%     19.289621   18.123875   -6.656732   -3.045162    7.959450    4.608041   
max     25.260000   25.260000    1.896280    3.310921   14.374000   10.750000   

            class  
count  194.000000  
mean     1.097938  
std      0.785685  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 7 columns):
RH       194 non-null float64
LH       194 non-null float64
RK       194 non-null float64
LK       194 non-null float64
RA       194 non-null float64
LA       194 non-null float64
class    194 non-null int64
dtypes: float64(6), int64(1)
memory usage: 10.7 KB


In [79]:
df["class"].value_counts()

1    73
2    70
0    51
Name: class, dtype: int64

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
X=df[df.columns[:-1]]
y=df['class']
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.3 ,random_state=21)

In [0]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

In [139]:
print("The shape of training data X is ", X_train.shape,"  and the type is ",type(X_train))
print("The shape of training data Y is ", y_train.shape,"  and the type is ",type(y_train))

The shape of training data X is  (135, 6)   and the type is  <class 'numpy.ndarray'>
The shape of training data Y is  (135,)   and the type is  <class 'pandas.core.series.Series'>


In [155]:
import ast
#@title Default title text
hidden = "50,3" #@param {type:"string"}
act = "logistic" #@param ["tanh", "logistic", "identity", "relu"]
hidden=ast.literal_eval(hidden)
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-4,hidden_layer_sizes=(hidden), random_state=21,activation=act)
clf.fit(X_train, y_train)
print("THE ACTIVATION FUNCTION IS :",act )
print(clf.predict(X_test[:1]),"::::::",y_test[:1])
print('Score on training data', clf.score(X_train,y_train)*100)
print('Score on testing data', clf.score(X_test,y_test)*100)
predictions = clf.predict(X_test)
print("The confusion matrix is \n",confusion_matrix(y_test,predictions))
print("The Classification report is \n",classification_report(y_test,predictions))
print("The Number of Output is :",clf.n_outputs_)
print("The Number of Iteration is :",clf.n_iter_)
print("The Number of Layer is :",clf.n_layers_)
print("The Loss is :",clf.loss_)
print("The Output is :",clf.classes_ )


THE ACTIVATION FUNCTION IS : logistic
[0] :::::: 21    0
Name: class, dtype: int64
Score on training data 77.77777777777779
Score on testing data 59.32203389830508
The confusion matrix is 
 [[18  0  0]
 [ 1 14  1]
 [ 0 22  3]]
The Classification report is 
              precision    recall  f1-score   support

          0       0.95      1.00      0.97        18
          1       0.39      0.88      0.54        16
          2       0.75      0.12      0.21        25

avg / total       0.71      0.59      0.53        59

The Number of Output is : 3
The Number of Iteration is : 201
The Number of Layer is : 4
The Loss is : 0.4358864151009168
The Output is : [0 1 2]
