In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv("gait.csv",names=["RH","LH","RK","LK","RA","LA","class"])

In [3]:
df.head()

RH     LH     RK     LK    RA    LA  class
0  24.61 -16.56  -3.94  -8.20 -1.70  9.81      0
1  24.45 -16.82  -6.66 -11.29 -3.25  8.26      0
2  24.13 -16.53  -9.45 -15.19 -4.68  5.52      0
3  23.68 -15.40 -12.26 -20.17 -5.08  1.11      0
4  22.96 -13.44 -14.76 -26.06 -4.17 -4.36      0

In [4]:
df.describe()

RH          LH          RK          LK          RA          LA  \
count  194.000000  194.000000  194.000000  194.000000  194.000000  194.000000   
mean     4.753114    3.894876  -22.831523  -20.170355    3.108274    0.699646   
std     15.544316   15.971763   20.869358   22.104877    6.019425    5.358262   
min    -21.978791  -23.849198  -69.740606  -68.433772  -14.070000  -14.070000   
25%    -10.146497  -10.786888  -33.700926  -34.560000   -0.007475   -3.091769   
50%      8.383730    7.659724  -15.376424  -12.436281    2.134878    0.361346   
75%     19.289621   18.123875   -6.656732   -3.045162    7.959450    4.608041   
max     25.260000   25.260000    1.896280    3.310921   14.374000   10.750000   

            class  
count  194.000000  
mean     1.097938  
std      0.785685  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 7 columns):
RH       194 non-null float64
LH       194 non-null float64
RK       194 non-null float64
LK       194 non-null float64
RA       194 non-null float64
LA       194 non-null float64
class    194 non-null int64
dtypes: float64(6), int64(1)
memory usage: 10.7 KB


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
X=df[df.columns[:-1]]
y=df['class']
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.75 ,random_state=44)

In [41]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test)  

In [42]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-4,hidden_layer_sizes=((6,6,3)), random_state=1,activation="identity")
clf.fit(X_train, y_train)
print(clf.predict(X_test[:1]),"::::::",y_test[:1])

[0] :::::: 46    0
Name: class, dtype: int64


In [43]:
print('Score on training data', clf.score(X_train,y_train)*100)
print('Score on testing data', clf.score(X_test,y_test)*100)
predictions = clf.predict(X_test)
print("The confusion matrix is \n",confusion_matrix(y_test,predictions))
print("The Classification report is \n",classification_report(y_test,predictions))

Score on training data 68.75
Score on testing data 54.794520547945204
The confusion matrix is 
 [[32 10  0]
 [ 3 29 20]
 [ 1 32 19]]
The Classification report is 
              precision    recall  f1-score   support

          0       0.89      0.76      0.82        42
          1       0.41      0.56      0.47        52
          2       0.49      0.37      0.42        52

avg / total       0.57      0.55      0.55       146



In [10]:
#Using SVM Classifier
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)
#print('Score on training data', svc.score(X_train,y_train)*100)
print('Score on testing data', svc.score(X_test,y_test)*100)

Score on testing data 28.767123287671232


In [11]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(max_depth=20)
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [12]:
clf.score(X_test,y_test)

0.4246575342465753